### ISSUE TITLE
Consider generating the output filename if none is specified

### ISSUE THREAD

**Issue by emersion** [emersion/grim#10]

**Comment by emersion** [comment]
Maybe save it in `$XDG_PICTURES_DIR` instead of the current directory? (With an override like `$GRIM_DEFAULT_DIR`)

**Comment by MicroJoe** [comment]
Here is the format that `scrot` uses for autogenerated filenames that could be reused in grim:

```
 2018-12-02-103517_1920x1080_scrot.png
```

**Comment by rvi64** [comment]
maybe output to stdout? that way it is easier to pipe to wl-copy, and redirecting with > is still easy.
also it would allow for something like tee to output to /tmp/screenshot.png AND to the clipboard.

**Comment by emersion** [comment]
No, it would be too easy to get junk in the terminal this way. grim supports `-` to pipe its output.

**Comment by emersion** [comment]
It's documented in the manpage: https://github.com/emersion/grim/blob/master/grim.1.scd#L17

I'm willing to add a "copy to clipboard" example once [this pull request](https://github.com/swaywm/wlr-protocols/pull/25) gets merged.

**Comment by ammgws** [comment]
@emersion This can be closed now :)
