### ISSUE TITLE
Have a non-zero exit code when a screenshot is cancelled?

### ISSUE THREAD

**Issue by PowerMan2206** [emersion/grim#110]
Would it be a good idea to have a non-zero exit code for cancelling a screenshot (like when using `grim` along with `slurp`)? I have a script that saves the screenshot to the clipboard and as a file, but it just saves a zero-byte file and gives me an empty clipboard when I cancel in the process. Checking the output could be a way, but an exit code would be neater.

**Comment by emersion** [comment]
How do you "cancel"? `grim` is a very short-lived process, it just captures one frame and exits. It has no concept of "cancelling".

**Comment by PowerMan2206** [comment]
As in, `grim -g $(slurp)`

**Comment by PowerMan2206** [comment]
Oh, I see
