### ISSUE TITLE
Cursor is captured without `-c` when `$WLR_NO_HARDWARE_CURSORS` is set to `1` in sway

### ISSUE THREAD

**Issue by blurgyy** [emersion/grim#112]
Hi, thank you for the great tool!

When I start sway with environment varialbe `$WLR_NO_HARDWARE_CURSORS=1` to use software cursors, `grim` will capture my cursor even if I did not pass it with `-c` flag.  This results in all my captured screenshots to contain a portion of my cursor, depending on the last position of my cursor:
Top-left: ![image](https://user-images.githubusercontent.com/44701880/146890484-49645afc-899c-45d6-b276-93ba4a2fc09c.png)
Top-right: ![image](https://user-images.githubusercontent.com/44701880/146890556-468808d3-c9fa-4570-be17-84272b17a9fb.png)
Bottom-left: ![image](https://user-images.githubusercontent.com/44701880/146890588-72420392-6cda-4069-9b5a-e1d75286ec39.png)
Bottom-right: ![image](https://user-images.githubusercontent.com/44701880/146890456-cce152af-b89e-4eb8-9bd3-c405d300bee3.png)

I also fail to grab pixel color with the method documented in README:

```shell
grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:-
```

Since my cursor is always captured by `grim`, the captured color is always the color of my cursor's tip, which is <code>#7C7C7C<span class="ml-1 d-inline-block border circle color-border-subtle" style="background-color: #7C7C7C; height: 8px; width: 8px;"></span></code> in my case.  I believe the issue mentioned in #96 is somewhat similar and might be related.

If I remove the `export WLR_NO_HARDWARE_CURSORS=1` befor starting sway, the problem goes away, cursor will then only be captured when I explicitly pass `-c` to `grim`, and pixel color grabbing also works properly.  If I keep using software cursors (i.e. setting `$WLR_NO_HARDWARE_CURSORS` to `1`), an undesireable workaround is to quickly move my cursor out of my selection region after selection with `slurp`, so that the cursor will not be captured by grim.

**Comment by emersion** [comment]
grim just passes the cursor flag to wlroots, this is a wlroots bug. IIRC we already have an opened issue for that.
