### ISSUE TITLE
With vulkan sway

### ISSUE THREAD

**Issue by chen244** [emersion/grim#119]
sway version 
```
sway version 1.7
```

I set 
```
WLR_RENDERER=vulkan
```
to /etc/environment

and when use grim , it report

```
failed to copy output eDP-1
```

Is it sway's bug or grim's bug?

My device

```
glxinfo | grep Device
    Device: Mesa Intel(R) Xe Graphics (TGL GT2) (0x9a49)
```

Thanks, I just want to ask if it is a bug, or how long will grim work correctly on vulkan

**Comment by mstoeckl** [comment]
> Is it sway's bug or grim's bug?

This is a known issue with the wlroots Vulkan backend, see https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3290 , and thus not a bug for grim.
