### ISSUE TITLE
Option to put image in clipboard

### ISSUE THREAD

**Issue by Limero** [emersion/grim#12]
It would be cool if there was an option to put the image into the clipboard instead of saving it to a file.

`-c` is the option used by other tools, such as gnome-screenshot, so grim should probably use the same.

**Comment by emersion** [comment]
There's no generic way to set the clipboard for a CLI program on Wayland.

For wlroots, we've been thinking of a clipboard manager protocol, but works hasn't started yet (https://github.com/swaywm/wlr-protocols/issues/20), and it's unclear if utilities like grim would be able to use it directly.

Even if all of this was fixed, I think this feature shouldn't be included in grim directly - instead, a program that sets the clipboard should be used (`grim - | copy-to-clipboard`).

**Comment by includereserved** [comment]
`grim - | xclip -i -selection clipboard -t image/png`?

**Comment by emersion** [comment]
Something like that, but `xclip` doesn't work on Wayland.

**Comment by Steverman** [comment]
Should work in Sway now
For selection:
`slurp | grim -g - - | xclip -i -selection c -t image/png` 
And your proposed command should work too:
`grim - | xclip -i -selection c -t image/png` 

Tested by pasting it into https://imgur.com/upload

**Comment by kushraj** [comment]
@Steverman does it still work ? In both cases, xclip has no image data in clipboard for me.

**Comment by unresolvedsymbol** [comment]
I'm pretty sure `xclip` will only work if you're pasting it into an xwayland app... Been using `wl-clipboard` in my screenshot script for ages now, works flawlessly.

**Comment by kushraj** [comment]
I tried pasting image on both firefox( imgur / whatsapp ) and gimp, should've work in them. Guess I will try wl-clipboard then

**Comment by unresolvedsymbol** [comment]
Firefox (and even it's ESR derivatives) has had Wayland support for a long time, make sure you've got MOZ_ENABLE_WAYLAND set or use the included `firefox-wayland` (`icecat-wayland` in my case) script to start it. Either way clipboard has always been strange to me, sometimes you need to middle click to paste the primary selection.

**Comment by unresolvedsymbol** [comment]
Also for people using chromium derivatives (chrome, brave, edge, etc) the flags you're looking for are `--enable-features=UseOzonePlatform --ozone-platform=wayland` :)

**Comment by kushraj** [comment]
> make sure you've got MOZ_ENABLE_WAYLAND

yeah I did, window protocol was also mentioned Wayland in about:suppport. nvm, since wl-clipboard is working well
