### ISSUE TITLE
Screenshooting individual windows

### ISSUE THREAD

**Issue by freed00m** [emersion/grim#19]
Hi,

would it be possible to screenshot a focused window?

scrot could do that `scrot -ue $f`. 

If slurp has some hidden option that does that I am sorry for asking in advance.

**Comment by emersion** [comment]
Indeed, that would be nice. It's currently blocked by lack of protocol to enumerate foreign windows. See https://github.com/swaywm/wlr-protocols/pull/26

**Comment by kellpossible** [comment]
No longer blocked?

**Comment by emersion** [comment]
The protocol isn't suitable for grim, since it allows too much (it would allow grim to manage windows, not just to list them). However https://github.com/emersion/slurp/pull/28 should greatly improve the situation.

**Comment by emersion** [comment]
Fixed in emersion/slurp#28
