### ISSUE TITLE
Capturing cursor without -c

### ISSUE THREAD

**Issue by genuinebyte** [emersion/grim#20]
I am using sway version 1.0-alpha.6-264-g56c388b5 (Oct 15 2018, branch 'master') and used a keyboard shortcut to perform the command below. In the lower left corner you can see that the cursor is present even though the `-c` option is not set.

![2018-10-16-181434](https://user-images.githubusercontent.com/37253114/47062030-b6b02a00-d199-11e8-97f5-21d28cb729a7.png)

**Comment by emersion** [comment]
Can you post your sway debug logs too?

**Comment by genuinebyte** [comment]
Here are the steps I took to reproduce it from a fresh start:
1. Reload sway ($mod+Shift+c)
2. Take one screenshot: `slurp | grim -g - ~/Pictures/screenshots/$(date +       '%Y-%m-%d-%H%M%S.png')` (I bound it to `$mod+$mod4+s`)
3. Take another screenshot: `slurp | grim -g - ~/Pictures/screenshots/$(date +       '%Y-%m-%d-%H%M%S.png')`

It seems to only happen after a reload of sway. When the mouse pointer is in the screenshot you can still see the plus-sign selector (for lack of a better term) that slurp brings up on top of it but as soon as you move the mouse it disappears. I tried to take a screenshot of this but the plus-sign selector doesn't show up. I have attached a sway log where I only performed these steps.
[good.log](https://github.com/emersion/grim/files/2486549/good.log)
