### ISSUE TITLE
grim fails to take screenshot in sway-1.0

### ISSUE THREAD

**Issue by mithodin** [emersion/grim#22]
I recently updated to sway-1.0 (running current master) on top of X (because of stupid reasons out of my control). When I try to take a screenshot with grim, I get the message "failed to copy output X11-1". Is there something I can do about this? Or is my setup just broken?

**Comment by emersion** [comment]
No, grim should work fine. It works fine on my system. Can you run `sway -d >sway.log 2&1`, try to screenshot and upload the log?

**Comment by mithodin** [comment]
There is one message that shows up when I try to take the screenshot:
2018-10-30 19:01:16 - [GLES2] GL_INVALID_OPERATION error generated. Invalid <format> parameter for current read framebuffer.

**Comment by emersion** [comment]
This is a wlroots issue then. Can you open an issue on the wlroots issue tracker, including the full debug log?

**Comment by mithodin** [comment]
will do.
