### ISSUE TITLE
Output to clipboard

### ISSUE THREAD

**Issue by deevus** [emersion/grim#23]
I was using `spectacle` which has a "Copy to clipboard" option. It would be cool if `grim` could do that.

**Comment by deevus** [comment]
Ok thanks.

Here's how I'm doing it for anyone else that arrives here looking. It saves the file and puts it in the clipboard. 

```bash
#!/bin/bash

FILE=$(xdg-user-dir PICTURES)/$(date +'%Y-%m-%d-%H%M%S_grim.png')

slurp | grim -g - $FILE
xclip -selection clipboard -t image/png < $FILE
```

**Comment by emersion** [comment]
As said in the other issue, you don't need to put it in a file:

```shell
grim - | xclip -i -selection clipboard -t image/png
```

**Comment by deevus** [comment]
Cheers. It so happens that I also want to save it. 

Appreciate the work you've done :+1:

**Comment by Bryophyllum** [comment]
This little project may have its use in this case
https://github.com/bugaevc/wl-clipboard
