### ISSUE TITLE
Doesn't handle space in a file name

### ISSUE THREAD

**Issue by chzzzh** [emersion/grim#26]
Grim prints everything, but what printed after a space.
ex: 'grim $(xdg-user-dir PICTURES)/Screenshots/$(date +'%x %T').png' will print only 12.11.2018.

**Comment by emersion** [comment]
The shell syntax requires you to quote command substitution.

```shell
grim "$(xdg-user-dir PICTURES)/Screenshots/$(date +'%x %T').png"
```
