### ISSUE TITLE
Add support for long options

### ISSUE THREAD

**Issue by MicroJoe** [emersion/grim#31]
I find myself calling `grim --help` a lot, and get this:

```
invalid option -- '-'
```

I think adding long options support should be done because a lot of other software propose short and long options, for example sway. With long options, we can even deduce what the option does without reading the facing text description, allowing faster discoverability of options.

Since the `main.c` is already using getopt, this should be fine to implement.

Also, IIRC getopt can generate an usage message from the list of (long option, short option, description). I think this should be done instead of having a static usage message. I have a program example that I could use to try to implement this if required.

**Comment by ammgws** [comment]
@emersion Sway has the same stance regarding GNU extensions but still uses `getopt_long`. Is that enough to convince you on this? Especially given `grim`'s largest user-base are `sway` users.

**Comment by emersion** [comment]
Closing, I won't be adding long options.
