### ISSUE TITLE
Allow output to clipboard instead of a file

### ISSUE THREAD

**Issue by MicroJoe** [emersion/grim#32]
Sometimes when doing quick screenshots the objective is just to paste them in a browser or software application that can handle images from the clipboard.

I do not know if the clipboard management is very different between Xorg and Wayland, but this could accelerate `screenshot -> open file in browser -> upload -> delete screenshot` workflow.

**Comment by emersion** [comment]
Duplicate of https://github.com/emersion/grim/issues/23
