### ISSUE TITLE
Make jpeg support optional

### ISSUE THREAD

**Issue by bschacht** [emersion/grim#34]
Hi,

i'm preparing a debian package of grim. I fear that the license of cairo_jpg.c is not DFSG compliant. Even if so, it would be an [embedded code copy](https://wiki.debian.org/EmbeddedCodeCopies), which is frowned up in Debian. But i could repackage before packaging for Debian- i would just need a switch to be able to compile without the two cairo_jpg files.

**Comment by emersion** [comment]
Cool to see someone's packaging this for Debian! Fixed in https://github.com/emersion/grim/commit/b5ad4f9db599cc58732b94cdd7e4fcdbe895af6a
