### ISSUE TITLE
b5ad4f9db599cc58732b94cdd7e4fcdbe895af6a broke png support

### ISSUE THREAD

**Issue by colemickens** [emersion/grim#35]
The switch statement falls through when built with JPEG support.

This results in all files being JPEG, despite their file suffix:

```
[cole@xeep:~]$ /nix/store/y5y1rwaqgvjam9pbz2n02my68vd6w2s7-grim-d2508c424465b9000ddfc5681256f53d2adb50be/bin/grim  ~/test.png

[cole@xeep:~]$ file ~/test.png
/home/cole/test.png: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 3840x2158, components 3
```

**Comment by colemickens** [comment]
Well, the case statement falls through either way, but it only matters when JPEG support is enabled...

**Comment by colemickens** [comment]
(noticed because my toolchain treated it as an error and I skimmed the code)

**Comment by emersion** [comment]
Eh, thanks, sorry about that!
