### ISSUE TITLE
Doesn't support tilde for home

### ISSUE THREAD

**Issue by paualberto** [emersion/grim#42]
This is a minor and unimportant issue, but it'd be cool to see this working.

Was trying to migrate from this which I used to use:  
```
maim -s "~/Pictures/screenshot/$(date +%F-%T).png"
```

And I found out appearently grim doesn't like `~`:  
```
[pau@pau-thinkpad ~]$ grim "$HOME/Pictures/screenshot/new.png"
[pau@pau-thinkpad ~]$ grim "~/Pictures/screenshot/new.png"
failed to write output file
```
(using 1.1)

**Comment by emersion** [comment]
We shouldn't need to do anything special for `~`. Make sure it's not quoted:

```
> echo ~
/home/simon
> echo "~"
~
```

**Comment by paualberto** [comment]
It works quoted as well in maim, I was hoping for a 100% drop-in replacement.
Sorry for the nitpicking :innocent:

**Comment by emersion** [comment]
Your shell is responsible for expanding `~`. This is not grim's job. ;)
