### ISSUE TITLE
Fish shell and grim slurp

### ISSUE THREAD

**Issue by asim215** [emersion/grim#46]
Hello. I tried to take a screenshot by doing the following:
```
Select a region and screenshoot it:
grim -g "$(slurp)" screenshot.png
```
And I get:
```
❯ grim -g "$(slurp)" screenshot.png
fish: $(...) is not supported. In fish, please use '(slurp)'.
grim -g "$(slurp)" screenshot.png
         ^
❯ grim -g '(slurp)' screenshot.png
invalid geometry
```
My setup: sway 1.0, fish 3.0.2, slurp 1.1.0-1, grim 1.1.0-2.
Is there a problem with fish compatibility?

**Comment by emersion** [comment]
Fish shell is not POSIX. You need to use the Fish-specific syntax: `grim -g "(slurp)" screenshot.png`

**Comment by asim215** [comment]
I use it, but got the same result:
```
❯ grim -g "(slurp)" screenshot.png
invalid geometry
```

**Comment by emersion** [comment]
I don't know Fish. Maybe this:

```
grim -g (slurp) screenshot.png
```

**Comment by asim215** [comment]
That's works. Thank you!
The problem was in fish:
```
❯ (slurp)
fish: Command substitutions not allowed
```
I find my answer here [https://superuser.com/questions/729405/how-to-do-command-substitution-in-fish-shell](url)
