### ISSUE TITLE
Allow recording screencats in combination with ffmepg

### ISSUE THREAD

**Issue by Tormen** [emersion/grim#48]
Hi,

reading [the last post here from dac-override](https://fedoramagazine.org/screencast-gnome-extension/), I would imagine that it could/should be possible to pipe the output of grim into ffmpeg and produce screencasts... potentially through slurp also for a specific region!

But I am not sure what the swaygrab -c did ... 

Maybe -c stood for continuous grabbing ??

Could you add such a "endless-loop" grabbing ... not sure how the handover to ffmpeg works yet... 

But I think this would be amazing :))

**Comment by emersion** [comment]
grim is not supposed to be used as a screen recording tool. For that, you can use https://github.com/ammen99/wf-recorder

**Comment by Tormen** [comment]
@emersion : Thanks for pointing me to wf-recorder.

Could be nice to add that to the wiki of swaywm (right below the link there to grim for screenshots). Could you do that? (or could I simply edit the wiki there ? - probably not, or?).

**Comment by emersion** [comment]
The swaywm wiki is editable. Please improve it!

**Comment by Tormen** [comment]
Thanks!

& done for this matter :))
& will do for future stuff :))
