### ISSUE TITLE
grim ignores XKB_DEFAULT_OPTIONS

### ISSUE THREAD

**Issue by buffet** [emersion/grim#49]
I got `XKB_DEFAULT_OPTIONS='compose:ralt,caps:swapescape'` in my envitronment (using sway).

When I invoke grim and try to cancel it with the Caps key nothing happens.  
When I press the actual Esc key it gets cancelled, but caps lock gets triggered as well.

**Comment by emersion** [comment]
Is this a slurp issue?

**Comment by buffet** [comment]
Oops yeah. Reopening over there. Confused them for a second.
