### ISSUE TITLE
Can’t take a screenshot of a non-active tty

### ISSUE THREAD

**Issue by sloonz** [emersion/grim#56]
1. Launch Sway in tty2 (WAYLAND_DISPLAY=wayland-0)
2. Launch another Sway instance in tty3 (WAYLAND_DISPLAY=wayland-1)
3. From the second Sway instance, launch WAYLAND_DISPLAY=wayland-0 grim test.png

grim then hangs until switching back to tty2 instead of immediately taking a screenshot of the first sway instance.

**Comment by emersion** [comment]
The rendering loop is paused on inactive TTYs, so that's expected.

**Comment by sloonz** [comment]
Same behavior on trying to capture a Sway instance running on a non-active workspace of a Sway instance. 

Do you know where in the wlroots code is this behavior implemented ? If yes, could you point it to me ?

**Comment by emersion** [comment]
See the screencopy implementation. A frame is requested when taking a screenshot.

Note that this isn't something I'd like to support.

**Comment by emersion** [comment]
Closing because this is a wlroots issue. Feel free to re-open there.
