### ISSUE TITLE
Not working Gnome on Manjaro 

### ISSUE THREAD

**Issue by xircon** [emersion/grim#58]
```
grim screenshot.png
wl_registry@2: error 0: invalid version for global wl_output (4): have 2, wanted 3
compositor doesn't support wlr-screencopy-unstable-v1
```
Any ideas?

**Comment by emersion** [comment]
GNOME doesn't support wlr-screencopy-unstable-v1, which is the protocol grim uses to take screenshots.

**Comment by xircon** [comment]
Thank you, will look for an alternative.

**Comment by intgr** [comment]
You should clearly document this in your project's README.

One would reasonably expect a "Wayland screenshot tool" to work with gnome-shell, one of the first adopters of Wayland.

**Comment by anarcat** [comment]
> One would reasonably expect a "Wayland screenshot tool" to work with gnome-shell, one of the first adopters of Wayland.

isn't it the reverse though, that GNOME should support the standards for screenshots? or is grim using an old version, or are they just going to be incompatible forever?
