### ISSUE TITLE
Capture screenshot in ChromeOS

### ISSUE THREAD

**Issue by mysteryjeans** [emersion/grim#61]
I need to capture screenshot in ChromeOS. As per your meson.build file all dependencies are installed using "crew" (off the shelf pkg manager), but the build got failed.

![Screenshot 2019-12-05 at 3 47 18 PM](https://user-images.githubusercontent.com/1826883/70228714-a16bd580-1776-11ea-9997-5c25bca3dc44.png)

Can you help us resolve the issue or point in right direction? I believe Chrome/Chromium OS runs on wayland since no X11 was found.

I am using OVA provided by neverware/cloudready for VMware, coming from windows & .NET background this is so far I have got..

**Comment by emersion** [comment]
I don't think ChromeOS supports the screencopy protocol grim uses. I believe they have their own screenshooting tools.

**Comment by mysteryjeans** [comment]
Please see this thread, according to dev here, ChromeOS uses wayland
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/a4zJM5S5C3Q

Following is the output of grim.

```
chronos@localhost ~/Downloads/grim/build $ screenshot
bash: screenshot: command not found
chronos@localhost ~/Downloads/grim/build $ which screenshot
which: no screenshot in (/usr/local/bin:/usr/bin:/bin:/opt/bin)
chronos@localhost ~/Downloads/grim/build $ ./grim screenshot.png
warning: zxdg_output_manager_v1 isn't available, guessing the output layout
compositor doesn't support wlr-screencopy-unstable-v1
```

**Comment by emersion** [comment]
ChromeOS uses Wayland but doesn't implement the Wayland protocol grim uses.
