### ISSUE TITLE
Provide more helpful error message(s)

### ISSUE THREAD

**Issue by ammgws** [emersion/grim#63]
When working on #62, I found that the error message displayed when `cairo_surface_to_xxx` fails is not very helpful when very long filenames are used:

```
> grim <morethan255charactershere> 
failed to write output file
```

The various strerrror functions don't really anything more helpful:
- strerror `Resource temporarily unavailable`
- cairo_status_to_string `error while writing to output stream`

Perhaps we could check the returned status code and if it is `CAIRO_STATUS_WRITE_ERROR` and our filepath is > `NAME_MAX` we could suggest that may be the issue in the error message.

The code in `cairo_surface_write_to_png` is:
```
    fp = fopen (filename, "wb");
    if (fp == NULL) {
	switch (errno) {
	case ENOMEM:
	    return _cairo_error (CAIRO_STATUS_NO_MEMORY);
	default:
	    return _cairo_error (CAIRO_STATUS_WRITE_ERROR);
	}
    }
```

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/grim/pull/64
