### ISSUE TITLE
List valid outputs

### ISSUE THREAD

**Issue by robsmith11** [emersion/grim#77]
grim is not very helpful when you want to screenshot a single monitor but have no idea what the outputs are called.  It should be possible to print a list of valid outputs.

**Comment by emersion** [comment]
No, this isn't grim's job. Use your compositor (e.g. on Sway, `swaymsg -t get_outputs`) or [wayland-info](https://gitlab.freedesktop.org/wayland/wayland-utils) (formerly known as weston-info).

**Comment by robsmith11** [comment]
Then you should at least define "output" more specifically in the help documentation.  It's a very generic term that could mean many things.  You're basically forcing users to read the source code of grim to understand how to use it.

**Comment by emersion** [comment]
"Output" is a Wayland term to mean screen/display/monitor/etc, and is used by e.g. the Sway config. Other terms are equally confusing. Documentation patches to clarify this are welcome.
