### ISSUE TITLE
print out the name/path of the screenshot written to

### ISSUE THREAD

**Issue by Inc0n** [emersion/grim#78]
I would like to integrate grim in my sway with mako, so I could notify myself where the screenshot has been saved at.

I couldn't find anything about in the man page. I assume it is not implemented, would be nice then if it gets implemented.

**Comment by emersion** [comment]
I'd suggest specifying an output path manually.

**Comment by Inc0ns1st3nt** [comment]
I would just want the name that grim has generated printed out while having not needed to generated a timestamped file name myself.

**Comment by kraftwerk28** [comment]
Why not just
```bash
name="/path/to/screenshots/grim-$(date +%F-%X).png"
grim $@ $name
notify-send "Screenshot saved at $name"
```

**Comment by Inc0n** [comment]
Thanks for the attached solution, which I also thank for a cue to close this year old issue.
