### ISSUE TITLE
Allow piping image data

### ISSUE THREAD

**Issue by katacarbix** [emersion/grim#84]
I take a lot of screenshots that I intend to only use once so I add them to my clipboard instead of saving to a file to reduce clutter on disk. With maim I can do this in a single command: `maim -u | xclip -selection clipboard -t image/png`. With grim I was expecting to be able to do something like `grim -o "$(swaymsg --type get_outputs --raw | jq --raw-output '.[] | select(.focused) | .name')" | wl-copy -t image/png` but that doesn't work. The only way I can imagine replicating this feature currently would be to save the screenshot to a file, copy the file contents, then delete the file.

Could this feature be added, either by automatically detecting a pipe or with a flag? Thank you.

**Comment by emersion** [comment]
From the man page:

> If output-file is -, grim will write the image to the standard output instead.

;)

**Comment by katacarbix** [comment]
Ah, I forgot to check _closed_ issues. Here's the solution I was looking for: https://github.com/emersion/grim/issues/51#issuecomment-495138394

**Comment by katacarbix** [comment]
Thanks a bunch!!
