### ISSUE TITLE
Grim isn't respecting $GRIM_DEFAULT_DIR

### ISSUE THREAD

**Issue by PopeRigby** [emersion/grim#86]
I'm trying to get Grim to put it's screenshots into the correct directory, but it's not respecting the `$GRIM_DEFAULT_DIR` environment variable. I'm using fish shell, and tried setting `$GRIM_DEFAULT_DIR` as a universal variable (makes it persists across sessions) and tried making it globally scoped.

OS: Arch Linux
Grim Version: 1.3.2
Fish Version: 3.2.1

**Comment by PopeRigby** [comment]
I just tested this with Bash as well, and that also didn't work. I run...
```
$ GRIM_DEFAULT_DIR="/home/user/test"
$ mkdir test
$ grim
```
and it outputs to my current working directory.

**Comment by PopeRigby** [comment]
I also built Grim from `master` and that doesn't work either.

**Comment by emersion** [comment]
Can't reproduce. Using `export GRIM_DEFAULT_DIR=/tmp` works in both bash and fish for me.

**Comment by PopeRigby** [comment]
What could the problem be then? `GRIM_DEFAULT_DIR` has the highest priority for where screenshots go, right?

**Comment by emersion** [comment]
In your bash session, you set a local shell variable, not an env variable.

**Comment by PopeRigby** [comment]
I see what the problem was. I set it to a global variable instead of a universal variable in fish. Maybe that could be specified in the docs to avoid confusion for future users?
