### ISSUE TITLE
XDG_PICTURES_DIR isn't an env variable

### ISSUE THREAD

**Issue by emersion** [emersion/grim#91]
According to [the spec](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/), `XDG_PICTURES_DIR` is an entry in `$XDG_CONFIG_HOME/user-dirs.dirs`. grim shouldn't try to read it from the env.

**Comment by spyjetfayed** [comment]
$GRIM_DEFAULT_DIR also doesn't seem to be working for me.

**Comment by emersion** [comment]
It works for me, and with so little information it's complicated to debug. Make sure you export is as an env variable.

**Comment by rjurga** [comment]
> $GRIM_DEFAULT_DIR also doesn't seem to be working for me.

If you use grim through a Sway keybind, as is common, make sure that `GRIM_DEFAULT_DIR` is exported in your `.bashrc` above the command that starts `sway`.
