### ISSUE TITLE
Update cairo_jpg

### ISSUE THREAD

**Issue by b1rger** [emersion/grim#99]
Hi,

now that #rahra/cairo_jpg/issues/2 was fixed, grim could ship the files with the updated license. `cairo_jpg` also fixed a memory leak in rahra/cairo_jpg/commit@2a0dff5ad313fdb8db3112eaf635bd56516ddf49. It might make sense to upstream the downstream changes before.

**Comment by emersion** [comment]
The memory leak doesn't affect grim, because grim only writes JPEG images, it doesn't read them.

**Comment by emersion** [comment]
Also note, our code has diverged quite a bit.
